definitions:
  dto.LoginReq:
    properties:
      password:
        maxLength: 20
        minLength: 6
        type: string
      phone:
        maxLength: 20
        minLength: 6
        type: string
    required:
    - password
    - phone
    type: object
  dto.LoginResp:
    properties:
      token:
        description: 登录token
        type: string
    type: object
  dto.RoleCreateReq:
    properties:
      code:
        maxLength: 64
        minLength: 1
        type: string
      name:
        maxLength: 255
        minLength: 1
        type: string
      resource_ids:
        items:
          type: string
        type: array
    required:
    - code
    - name
    type: object
  dto.RoleDeleteReq:
    properties:
      ids:
        items:
          type: string
        type: array
    required:
    - ids
    type: object
  dto.RoleUpdateReq:
    properties:
      name:
        maxLength: 255
        minLength: 1
        type: string
      resource_ids:
        items:
          type: string
        type: array
    required:
    - name
    type: object
  dto.RoleUpdateStatusReq:
    properties:
      status:
        $ref: '#/definitions/model.EnabledStatus'
    type: object
  model.EnabledStatus:
    enum:
    - 1
    - 2
    format: int32
    type: integer
    x-enum-comments:
      Disabled: 禁用
      Enabled: 启用
    x-enum-descriptions:
    - 启用
    - 禁用
    x-enum-varnames:
    - Enabled
    - Disabled
  model.Role:
    properties:
      code:
        type: string
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      status:
        $ref: '#/definitions/model.EnabledStatus'
      updated_at:
        type: string
    type: object
  response.pageData:
    properties:
      list: {}
      total:
        type: integer
    type: object
  response.response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: 登录用户
      parameters:
      - description: 登录请求
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/dto.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.response'
            - properties:
                data:
                  $ref: '#/definitions/dto.LoginResp'
              type: object
      summary: 登录
      tags:
      - 认证
  /api/v1/role:
    delete:
      consumes:
      - application/json
      description: 删除角色
      parameters:
      - description: 删除角色请求
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/dto.RoleDeleteReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.response'
      summary: 删除角色
      tags:
      - 角色
    get:
      consumes:
      - application/json
      description: 分页查询角色
      parameters:
      - in: query
        name: name
        type: string
      - in: query
        minimum: 1
        name: page
        type: integer
      - in: query
        minimum: 1
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.response'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/response.pageData'
                  - properties:
                      List:
                        items:
                          $ref: '#/definitions/model.Role'
                        type: array
                    type: object
              type: object
      summary: 分页查询角色
      tags:
      - 角色
    post:
      consumes:
      - application/json
      description: 创建角色
      parameters:
      - description: 创建角色请求
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/dto.RoleCreateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.response'
      summary: 创建角色
      tags:
      - 角色
  /api/v1/role/{id}:
    get:
      consumes:
      - application/json
      description: 获取角色详情
      parameters:
      - description: 角色ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.response'
      summary: 获取角色详情
      tags:
      - 角色
    put:
      consumes:
      - application/json
      description: 更新角色
      parameters:
      - description: 角色ID
        in: path
        name: id
        required: true
        type: string
      - description: 更新角色请求
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/dto.RoleUpdateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.response'
      summary: 更新角色
      tags:
      - 角色
  /api/v1/role/{id}/status:
    put:
      consumes:
      - application/json
      description: 更新角色状态
      parameters:
      - description: 角色ID
        in: path
        name: id
        required: true
        type: string
      - description: 更新角色状态请求
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/dto.RoleUpdateStatusReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.response'
      summary: 更新角色状态
      tags:
      - 角色
  /api/v1/role/option:
    get:
      consumes:
      - application/json
      description: 角色选项
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.Role'
                  type: array
              type: object
      summary: 角色选项
      tags:
      - 角色
swagger: "2.0"
